# Generated by Django 4.2.4 on 2023-12-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestorVehiculos", "0002_tipo_alter_vehiculo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="tipo",
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name="Tipo",
        ),
    ]
